notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"
language: python
python:
  - "2.6"
  - "2.7"
env: C_INCLUDE_PATH=/usr/lib/openmpi/include PETSC_CONFIGURE_OPTIONS="--with-fortran-interfaces=1 --with-c++-support"
# command to install dependencies
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -qq build-essential python-dev git-core mercurial \
    cmake cmake-curses-gui gmsh python-pip swig libhdf5-openmpi-dev \
    libopenmpi-dev openmpi-bin libblas-dev liblapack-dev gfortran triangle-bin"
  - "pip install -r requirements-minimal.txt --use-mirrors"
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install argparse ordereddict; fi
install: "python setup.py develop"
# command to run tests
script:
  - make lint
  - PYTEST_VERBOSE=1 make unit_sequential regression_sequential unit_openmp regression_openmp
